#!/user/bin/env bash
# A bash script to transfer a file from loacal machine to serever

if [ "$#" -lt 4 ]; then
	echo :Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i $4 -o StrictHostKeyChecking=0 $1 $3@$2:~/
