#!/usr/bin/env bash
#This script installs nginx

# Install nginx
sudo apt-get update
sudo apt-get -y install nginxi

# Configure nginx to listen on port 80 and serve "Hello World!" at the root
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
sudo service nginx restart
